In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("11_adspend_vs_website_visits.csv")

df.head()

,ad_spend_usd,marketing_spend_usd,competitor_price_usd,season_index,website_visits
0,207.0,72.97,54.28,2,764
1,71.0,496.65,24.5,2,215
2,821.0,492.13,39.12,2,3377
3,400.0,423.65,30.72,4,1900
4,618.0,151.45,35.25,3,2006

In [3]:
df.shape

(311, 5)

In [4]:
df.columns

Index(['ad_spend_usd', 'marketing_spend_usd', 'competitor_price_usd',
       'season_index', 'website_visits'],
      dtype='object')

In [5]:
df.isnull().sum()

ad_spend_usd             6
marketing_spend_usd     14
competitor_price_usd     4
season_index             7
website_visits           3
dtype: int64

In [6]:
df["ad_spend_usd"] = pd.to_numeric(
    df["ad_spend_usd"],
    errors="coerce"
)

df["marketing_spend_usd"] = pd.to_numeric(
    df["marketing_spend_usd"],
    errors="coerce"
)

df["competitor_price_usd"] = pd.to_numeric(
    df["competitor_price_usd"],
    errors="coerce"
)

df["season_index"] = pd.to_numeric(
    df["season_index"],
    errors="coerce"
)

df["website_visits"] = pd.to_numeric(
    df["website_visits"],
    errors="coerce"
)

df.dtypes

ad_spend_usd            float64
marketing_spend_usd     float64
competitor_price_usd    float64
season_index            float64
website_visits          float64
dtype: object

In [7]:
df.isnull().sum()

ad_spend_usd            12
marketing_spend_usd     16
competitor_price_usd     9
season_index             9
website_visits           4
dtype: int64

In [8]:
df = df.dropna()

df.shape

(264, 5)

In [9]:
df.head()

,ad_spend_usd,marketing_spend_usd,competitor_price_usd,season_index,website_visits
0,207.0,72.97,54.28,2.0,764.0
1,71.0,496.65,24.50,2.0,215.0
2,821.0,492.13,39.12,2.0,3377.0
3,400.0,423.65,30.72,4.0,1900.0
4,618.0,151.45,35.25,3.0,2006.0

In [10]:
df.dtypes

ad_spend_usd            float64
marketing_spend_usd     float64
competitor_price_usd    float64
season_index            float64
website_visits          float64
dtype: object

In [ ]:
df.isnull().sum()